"""
Email delivery for completed HCAI compliance reports.

Sends the PDF report (and a summary) to the customer email when a job completes.

Configuration (environment variables)
--------------------------------------
SMTP_HOST       SMTP server host       (default: smtp.gmail.com)
SMTP_PORT       SMTP port              (default: 587)
SMTP_USER       Login username / email
SMTP_PASSWORD   Login password (app password for Gmail)
EMAIL_FROM      Sender display address (default: SMTP_USER)
EMAIL_REPLY_TO  Reply-to address       (optional)

If SMTP_USER is not set, email delivery is silently skipped (dev mode).
"""

from __future__ import annotations

import os
import smtplib
import ssl
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

from src.monitoring.logger import get_logger

log = get_logger(__name__)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

SMTP_HOST      = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT      = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER      = os.getenv("SMTP_USER", "")
SMTP_PASSWORD  = os.getenv("SMTP_PASSWORD", "")
EMAIL_FROM     = os.getenv("EMAIL_FROM", SMTP_USER)
EMAIL_REPLY_TO = os.getenv("EMAIL_REPLY_TO", "")
APP_BASE_URL   = os.getenv("APP_BASE_URL", "http://localhost:8000")


# ---------------------------------------------------------------------------
# Send
# ---------------------------------------------------------------------------

def send_report_email(
    to_email: str,
    project_name: str,
    job_id: str,
    pdf_path: Path | None,
    total_violations: int,
    critical_count: int,
    high_count: int,
) -> bool:
    """
    Send the compliance report PDF to the customer.

    Returns True on success, False on failure.
    If SMTP is not configured, logs a warning and returns False.
    """
    if not SMTP_USER or not SMTP_PASSWORD:
        log.info(
            "SMTP not configured — skipping email for job %s. "
            "Set SMTP_USER and SMTP_PASSWORD to enable email delivery.",
            job_id,
        )
        return False

    subject = f"Your BlueprintIQ Compliance Report — {project_name}"
    results_url = f"{APP_BASE_URL}/?job_id={job_id}"

    # ── Build HTML body ──────────────────────────────────────────────────
    severity_summary = ""
    if critical_count:
        severity_summary += f"<li><strong style='color:#C53030'>{critical_count} Critical</strong> finding(s) require immediate attention</li>"
    if high_count:
        severity_summary += f"<li><strong style='color:#C05621'>{high_count} High</strong> finding(s) need resolution before HCAI submission</li>"

    html_body = f"""
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"/></head>
<body style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;color:#2D3748;">
  <div style="background:#1A365D;padding:24px 32px;border-radius:8px 8px 0 0;">
    <h1 style="color:white;margin:0;font-size:20px;">BlueprintIQ Compliance Report Ready</h1>
    <p style="color:#BEE3F8;margin:6px 0 0;font-size:14px;">{project_name}</p>
  </div>
  <div style="background:#F7FAFC;padding:24px 32px;border:1px solid #E2E8F0;border-top:none;border-radius:0 0 8px 8px;">

    <p style="font-size:15px;">Your compliance analysis is complete.</p>

    <div style="background:white;border:1px solid #E2E8F0;border-radius:8px;padding:16px 20px;margin:16px 0;">
      <p style="font-size:13px;color:#718096;margin:0 0 8px;">Summary</p>
      <p style="font-size:24px;font-weight:bold;color:#1A365D;margin:0 0 8px;">{total_violations} Findings</p>
      {"<ul style='font-size:14px;margin:0;padding-left:20px;'>" + severity_summary + "</ul>" if severity_summary else "<p style='font-size:14px;color:#38A169;'>No critical or high-severity issues detected.</p>"}
    </div>

    <p style="font-size:14px;">
      The full PDF report is attached to this email. You can also view your results online:
    </p>

    <div style="text-align:center;margin:20px 0;">
      <a href="{results_url}"
         style="background:#2B6CB0;color:white;padding:12px 28px;border-radius:8px;text-decoration:none;font-weight:bold;font-size:15px;">
        View Report Online
      </a>
    </div>

    <hr style="border:none;border-top:1px solid #E2E8F0;margin:24px 0;"/>

    <p style="font-size:12px;color:#A0AEC0;margin:0;">
      <strong>Disclaimer:</strong> This report is generated by an automated compliance engine and is
      intended as a preliminary screening tool only. It does not constitute a licensed engineering or
      architectural review. Consult a California-licensed professional before submitting to HCAI.
    </p>
    <p style="font-size:12px;color:#A0AEC0;margin-top:8px;">
      Questions? Reply to this email or contact <a href="mailto:hello@blueprintiq.net" style="color:#4299E1;">hello@blueprintiq.net</a>
    </p>
  </div>
</body>
</html>
"""

    text_body = (
        f"Your HCAI Compliance Report is ready — {project_name}\n\n"
        f"Total findings: {total_violations}\n"
        f"View online: {results_url}\n\n"
        "The PDF report is attached.\n\n"
        "Disclaimer: Automated tool only. Not a substitute for licensed engineer review."
    )

    # ── Build MIME message ───────────────────────────────────────────────
    msg = MIMEMultipart("mixed")
    msg["Subject"] = subject
    msg["From"]    = EMAIL_FROM or SMTP_USER
    msg["To"]      = to_email
    if EMAIL_REPLY_TO:
        msg["Reply-To"] = EMAIL_REPLY_TO

    alt = MIMEMultipart("alternative")
    alt.attach(MIMEText(text_body, "plain", "utf-8"))
    alt.attach(MIMEText(html_body, "html",  "utf-8"))
    msg.attach(alt)

    # Attach PDF if it exists
    if pdf_path and Path(pdf_path).exists():
        with open(pdf_path, "rb") as f:
            pdf_data = f.read()
        attachment = MIMEApplication(pdf_data, _subtype="pdf")
        safe_name = project_name.replace("/", "-").replace("\\", "-")[:50]
        attachment.add_header("Content-Disposition", "attachment", filename=f"{safe_name}_HCAI_Report.pdf")
        msg.attach(attachment)

    # ── Send via SMTP ────────────────────────────────────────────────────
    try:
        context = ssl.create_default_context()
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls(context=context)
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(EMAIL_FROM or SMTP_USER, to_email, msg.as_string())

        log.info("Report email sent to %s for job %s", to_email, job_id)
        return True

    except smtplib.SMTPException as e:
        log.error("Failed to send report email to %s for job %s: %s", to_email, job_id, e)
        return False
